export const errorMessages = Object.freeze({
  INVALID_EMAIL: "Invalid email",
  INVALID_PASSWORD: "Invalid password",
  EMAIL_EXISTED: "Email already exists",
  NOT_FOUND: "Not found",
  ERROR_SERVER: "Server error",
  EMAIL_EXIST: "Email already exists",
  EMAIL_NOT_FOUND: "Email not found",
  PASSWORD_NOT_MATCH: "Password not",
  TOKEN_INVALID: "Token invalid",
  DELETE_FAIL: "Delete fail",
  INVALID_BODY_REQUEST: "Invalid body request!",
  PERMISSION_DENIED: "Permission denied!",
});

export const successMessages = Object.freeze({
  REGISTER_SUCCESS: "Register successfully!",
  LOGIN_SUCCESS: "Login successfully!",
  GET_USER_SUCCESS: "Get user successfully!",
  UPDATE_USER_SUCCESS: "Update user successfully!",
  DELETE_USER_SUCCESS: "Delete user successfully!",
  GET_PROFILE_SUCCESS: "Get profile successfully!",
  RESET_PASSWORD_SUCCESS: "Reset password successfully!",
  UPDATE_PROFILE_SUCCESS: "Update profile successfully!",
  GET_PRODUCT_SUCCESS: "Get product successfully!",
  CREATE_PRODUCT_SUCCESS: "Create product successfully!",
  UPDATE_PRODUCT_SUCCESS: "Update product successfully!",
  DELETE_PRODUCT_SUCCESS: "Delete product successfully!",
  DELETE_CATEGORY_SUCCESS: "Delete Category successfully!",
  GET_CATEGORY_SUCCESS: "Get category successfully!",
  CREATE_CATEGORY_SUCCESS: "Create category successfully!",
  UPDATE_CATEGORY_SUCCESS: "Update category successfully!",
});
